on: push
name: ğŸš€ Deploy on push
jobs:
  private-deploy:
    name: ğŸ‰ Private Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    - name: Composer install
      run: composer update
