on: push
name: ðŸš€ Deploy API Engine on push
jobs:
  api-engine-deploy:
    name: ðŸŽ‰ Private Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
    - name: Composer install
      run: composer require intervention/image
    - name: ðŸ“‚ Private Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: holydemo.com
        username: u483864572.holydemo_ftp_admin
        password: ${{secrets.FTP_PASSWORD}}
        port: 21
        server-dir : / 
        exclude: |
          **/.git*
          **/.git*/**
          **/public_html/**
          **/vendor/**
          **/storage/**
          **/.env*



